#name: CI
#
#on:
#  push:
#    branches: [ "main" ]
#
#jobs:
#  build:
#    runs-on: ubuntu-latest
#
#    steps:
#      - uses: actions/checkout@v4
#
#      - name: JDK 21 설정
#        uses: actions/setup-java@v4
#        with:
#          java-version: '21'
#          distribution: 'temurin'
#
#      - name: Maven Test
#        run: mvn clean test
#
#      - name: Maven Build
#        run: mvn clean package -DskipTests
#
#      - name: GCP 인증
#        uses: google-github-actions/auth@v2
#        with:
#          credentials_json: ${{ secrets.GCP_SA_KEY }}
#
#      - name: Docker 인증
#        run: gcloud auth configure-docker asia-northeast3-docker.pkg.dev
#
#      - name: Docker Build
#        run: |
#          docker build -t ${{ secrets.GCP_ARTIFACT_REGISTRY_PATH }}/pbb_api:${{ github.sha }} .
#
#      - name: Docker Push
#        run: |
#          docker push ${{ secrets.GCP_ARTIFACT_REGISTRY_PATH }}/pbb_api:${{ github.sha }}
